targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          - lib/src/data/models/**/*.dart
      freezed:
        enabled: true
        generate_for:
          - lib/src/data/models/**/*.dart
